### ISSUE TITLE
Duplicate print this page button in guidance publications

### ISSUE THREAD

**Issue by alex-ju** [alphagov/government-frontend#1907]
We show two instances of the 'print this page' button which overlap at a certain scroll position.

Page example: https://www.gov.uk/government/publications/actions-for-schools-during-the-coronavirus-outbreak/guidance-for-full-opening-schools

## Visual example

![2020-11-09 at 13 16 14](https://user-images.githubusercontent.com/788096/98545922-19e3ec00-228e-11eb-8848-4c0a9c5dd7fa.gif)

**Comment by alex-ju** [comment]
The same issue causes overlap with the feedback component further down the page.
<img width="1109" alt="Screenshot 2021-02-24 at 10 22 10" src="https://user-images.githubusercontent.com/788096/109137573-40e8ff80-7751-11eb-908e-9ddc51f45a60.png">

**Comment by DilwoarH** [comment]
Raised again on: https://github.com/alphagov/govuk_publishing_components/issues/1970

**Comment by DilwoarH** [comment]
I will speak with the designer to see if we can come up with a solution

**Comment by danacotoran** [comment]
For whoever gets round to fixing this, it can be reproduced by:
1. clearing cookies so that you see the cookie banner at the top
2. either accept/reject cookies – choice doesn't matter, what matters is that the cookie banner changes state

Now if you scroll down to the bottom of the feedback banner you would be able to see the issue [Alex shows here](https://github.com/alphagov/government-frontend/issues/1907#issuecomment-785777630).

Thought I'd document this in the issue.

**Comment by DilwoarH** [comment]
Thanks for this @danacotoran - I have spoken with the interaction designer who worked on the original work with me and we've come up with a few solutions that might solve the problem.

**Comment by DilwoarH** [comment]
@alex-ju @chris-gds @danacotoran - I spoke to the designer who was originally working with me on this and we came to the conclusion that item lists longer than 10 would create duplicates in different screen sizes. Please have a look at the PR that I raised: https://github.com/alphagov/government-frontend/pull/2056

**Comment by andysellick** [comment]
Closing as this page has been changed to not have a duplicate button: https://github.com/alphagov/government-frontend/pull/2493
