### ISSUE TITLE
Contents link flashes strangely

### ISSUE THREAD

**Issue by fofr** [alphagov/government-frontend#743]
On a page with contents and short content, the contents link flashes in and out:
https://www.gov.uk/government/collections/hmrcs-annual-report-and-accounts

![ezgif-5-fc33ea0928](https://user-images.githubusercontent.com/319055/36020772-ae2e211c-0d7b-11e8-87a6-66fed03f17a3.gif)

**Comment by steventux** [comment]
@fofr I believe this will be fixed by the short contents list work @emmabeynon has been doing https://github.com/alphagov/government-frontend/pull/719
This is deployed to integration https://www-origin.integration.publishing.service.gov.uk/government/collections/hmrcs-annual-report-and-accounts and won't suffer the same flashing behaviour because shorter content lists won't display the contents list links or the (back to) contents link below the content.

**Comment by steventux** [comment]
This is now fixed by https://github.com/alphagov/government-frontend/pull/719 and deployed to production.
